<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Movie Review Generator</title>
  <style>
    body {
      background-color: #1b3d1b;
      color: #f0fff0;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }

    .form-container {
      background-color: #2e5939;
      padding: 30px;
      border-radius: 12px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
      width: 380px;
      text-align: center;
    }

    h2 {
      margin-bottom: 20px;
      color: #c7f9cc;
    }

    label {
      display: block;
      margin-bottom: 10px;
      color: #e2fce2;
      font-weight: bold;
      text-align: left;
    }

    input[type="text"] {
      width: 100%;
      padding: 10px;
      border: none;
      border-radius: 8px;
      margin-bottom: 20px;
      background-color: #c7f9cc;
      color: #1b3d1b;
    }

    .stars {
      display: flex;
      justify-content: space-between;
      flex-wrap: wrap;
      margin-bottom: 20px;
      gap: 6px;
    }

    .star {
      background-color: #40916c;
      color: white;
      border: none;
      border-radius: 6px;
      width: 30px;
      height: 30px;
      font-weight: bold;
      cursor: pointer;
      transition: background-color 0.2s;
    }

    .star.selected {
      background-color: #74c69d;
    }

    input[type="submit"] {
      width: 100%;
      padding: 12px;
      background-color: #52b788;
      border: none;
      border-radius: 8px;
      color: white;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #40916c;
    }

    input[type="hidden"] {
      display: none;
    }
  </style>
</head>
<body>

  <div class="form-container">
    <h2>Movie Review Generator</h2>
    <form action="generateReview.php" method="POST">
      <label for="movieTitle">Movie Title</label>
      <input type="text" id="movieTitle" name="movieTitle" required>

      <label>Your Score (1–10)</label>
      <div class="stars" id="starContainer">
        <!-- Star buttons will be generated by JavaScript -->
      </div>
      <input type="hidden" id="score" name="score" required>

      <input type="submit" value="Generate Review">
    </form>
  </div>

  <script>
    const starContainer = document.getElementById('starContainer');
    const hiddenScore = document.getElementById('score');

    for (let i = 1; i <= 10; i++) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'star';
      btn.textContent = i;
      btn.dataset.value = i;

      btn.addEventListener('click', () => {
        hiddenScore.value = i;

        // Remove selected class from all
        document.querySelectorAll('.star').forEach(star => star.classList.remove('selected'));
        // Highlight the selected star
        btn.classList.add('selected');
      });

      starContainer.appendChild(btn);
    }
  </script>

</body>
</html>
